--- 
title: "Registration and abstract submission"
---


<!-- main text -->

<div  style="max-width: 55rem; float:left;">
The registration form is available [here`r fontawesome::fa(name = "fas fa-link", fill = "bg-primary")`](`r REGISTRATION_FORM`).

Registration is **free** and will be open until `r REGISTRATION_ENDS`. If you want to submit an abstract
to be considered for presentation, have it ready at the time of registration, as
you will be requested to upload it. The document should follow the abstract 
formatting guidelines described below. Abstract sumission will end `r REGISTRATION_ENDS`. All 
abstracts will be reviewed by the [organizers](https://medicine.yale.edu/lab/kleinstein/). Acceptance is based on 
scientific content and relevance to the meeting goal, which is to showcase 
the use of a variety of the Immcantation tools in advacing
knowledge of the adaptive immune receptor repertoire. Selected speakers will be contacted
by email on `r CONTACT_SPEAKERS`. The final schedule and selected abstracts will be published on `r FINAL_SCHEDULE`.

### Abstract formatting guidelines

An abstract template is available for download <a href="static/AbstractTemplate.rtf">here`r fontawesome::fa(name = "fas fa-file", fill = "bg-primary")`</a>.

* One abstract per presenting author.

* 2500 characters total (including *all text and spaces*: title, authors, abstract...).

* Title in bold text.

* Title cannot be in all capital letters.

* Presenter author must be underlined.

* Use the asterisk symbol (*) to signify the Corresponding Author.

* No comments, text or image boxes in the abstract.
    
* .rtf  documents only.
</div>


<!-- side box -->
<div class="card text-white bg-primary mb-3" style="max-width: 35rem; float:right;">
<div class="card-body">
<div class="card-title"></div>
<div class="card-text">

<button type="button" class="btn btn-outline-primary">[Go to the registration form](`r REGISTRATION_FORM`)</button>

Important dates: 

* **Abstract submission ends**: `r SUBMISSION_ENDS`

* **Contact selected speakers**: `r CONTACT_SPEAKERS`

* **Registration ends**: `r REGISTRATION_ENDS`

* **Final schedule:**: `r FINAL_SCHEDULE`

</div></div>
 </div>